### ISSUE TITLE
MongoDB port not getting to template

### ISSUE THREAD

**Issue by malkolm** [hudl/signalfx-cookbook#4]
in signalfx-cookbook::mongodb, the attribute for ['mongodb']['port'] doesn't appear to be getting set correctly.  This results in port 27017 being used in all of the collectd.  We think it ran in stage properly, but we saw only the default port in prod.  It needs investigation.

**Comment by acsportstec** [comment]
I believe this issue is caused by the config node not correctly being set on role_mongo, can be seen [here](https://github.com/hudl/role_mongo/blob/master/attributes/default.rb#L21)

I have added the following in a new branch [here](https://github.com/hudl/role_mongo/blob/beta-node-port-selection/attributes/default.rb#L48), I am not sure if this would correctly resolve the issue?

```
          if node.name.split('-')[3].eql?('cfg')
            default["mongodb"]["node_type"] = "config"
          end
```

**Comment by malkolm** [comment]
I figured it out.  in attributes/mongodb.rb the node attribute wasn't being checked for properly.
